Repository SonarSource/eslint-plugin-sonarjs, pull requests merged in 2018-04, with the labels that each got.

#23 simplify rules declaration
  src/index.ts
  tests/config-recommended.test.ts
  tests/index.test.ts
Labels: review

#25 add rule no-use-of-empty-return-value
  README.md
  docs/rules/no-use-of-empty-return-value.md
  ruling/index.ts
  ruling/snapshots/no-use-of-empty-return-value
  src/index.ts
  src/rules/no-use-of-empty-return-value.ts
  src/utils/nodes.ts
  tests/rules/no-use-of-empty-return-value.test.ts
Labels: in progress

#27 add no-identical-functions rule
  README.md
  docs/rules/no-identical-functions.md
  ruling/snapshots/no-identical-functions
  src/index.ts
  src/rules/no-identical-functions.ts
  src/utils/locations.ts
  tests/rules/no-identical-functions.test.ts
Labels: in progress

#29 add no-all-duplicated-branches rule
  README.md
  docs/rules/no-all-duplicated-branches.md
  ruling/snapshots/no-all-duplicated-branches
  src/index.ts
  src/rules/no-all-duplicated-branches.ts
  src/rules/no-duplicated-branches.ts
  src/utils/conditions.ts
  src/utils/equivalence.ts
  tests/rules/no-all-duplicated-branches.test.ts
Labels: status: in progress

#24 add cognitive-complexity rule
  README.md
  docs/rules/cognitive-complexity.md
  ruling/snapshots/cognitive-complexity
  src/index.ts
  src/rules/cognitive-complexity.ts
  src/utils/locations.ts
  src/utils/nodes.ts
  tests/rules/cognitive-complexity.test.ts
Labels: status: in progress

#30 add no-extra-arguments rule
  README.md
  docs/rules/no-extra-arguments.md
  ruling/snapshots/no-extra-arguments
  src/index.ts
  src/rules/no-extra-arguments.ts
  src/utils/nodes.ts
  tests/rules/no-extra-arguments.test.ts
Labels: status: in review

#31 add rule no-one-iteration-loop
  README.md
  docs/rules/no-one-iteration-loop.md
  ruling/snapshots/no-one-iteration-loop
  src/index.ts
  src/rules/no-one-iteration-loop.ts
  src/utils/nodes.ts
  tests/rules/no-one-iteration-loop.test.ts
Labels: status: in progress

#32 add no-identical-conditions rule
  README.md
  docs/rules/no-identical-conditions.md
  ruling/snapshots/no-identical-conditions
  src/index.ts
  src/rules/no-identical-conditions.ts
  tests/rules/no-identical-conditions.test.ts
Labels: status: in progress

#33 add prefer-immediate-return rule
  README.md
  docs/rules/prefer-immediate-return.md
  ruling/snapshots/prefer-immediate-return
  src/index.ts
  src/rules/prefer-immediate-return.ts
  src/utils/nodes.ts
  tests/rules/prefer-immediate-return.test.ts
Labels: status: in progress

#34 add prefer-single-boolean-return rule
  README.md
  docs/rules/prefer-single-boolean-return.md
  ruling/snapshots/prefer-single-boolean-return
  src/index.ts
  src/rules/prefer-single-boolean-return.ts
  src/utils/nodes.ts
  tests/rules/prefer-single-boolean-return.test.ts
Labels: status: in progress

#35 add github issue and pull request templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: status: in review

#36 add rule no-element-overwrite
  README.md
  docs/rules/no-element-overwrite.md
  ruling/snapshots/no-element-overwrite
  src/index.ts
  src/rules/no-element-overwrite.ts
  src/utils/nodes.ts
  tests/rules/no-element-overwrite.test.ts
Labels: status: in progress

#41 add eslint
  .eslintrc.js
  .travis.yml
  package.json
  ruling/.eslintrc.js
  ruling/index.ts
  src/rules/no-use-of-empty-return-value.ts
  tests/rules/no-identical-expressions.test.ts
  tests/rules/no-use-of-empty-return-value.test.ts
  yarn.lock
Labels: status: in review

#52 add links to RSPEC
  src/rules/cognitive-complexity.ts
  src/rules/no-all-duplicated-branches.ts
  src/rules/no-duplicated-branches.ts
  src/rules/no-element-overwrite.ts
  src/rules/no-extra-arguments.ts
  src/rules/no-identical-conditions.ts
  src/rules/no-identical-expressions.ts
  src/rules/no-identical-functions.ts
  src/rules/no-one-iteration-loop.ts
  src/rules/no-redundant-boolean.ts
  src/rules/no-small-switch.ts
  src/rules/no-use-of-empty-return-value.ts
  src/rules/prefer-immediate-return.ts
  src/rules/prefer-single-boolean-return.ts
Labels: status: in progress

#55 use babel-eslint for ruling
  package.json
  ruling/index.ts
  ruling/snapshots/cognitive-complexity
  ruling/snapshots/no-all-duplicated-branches
  ruling/snapshots/no-duplicated-branches
  ruling/snapshots/no-identical-expressions
  ruling/snapshots/no-identical-functions
  ruling/snapshots/no-one-iteration-loop
  ruling/snapshots/no-redundant-boolean
  ruling/snapshots/no-small-switch
  ruling/snapshots/prefer-immediate-return
  ruling/snapshots/prefer-single-boolean-return
  yarn.lock
Labels: status: in review

#56 add code fix to prefer-immediate-return
  src/rules/prefer-immediate-return.ts
  tests/rules/prefer-immediate-return.test.ts
Labels: status: in progress

#54 add rule prefer-while
  README.md
  docs/rules/prefer-while.md
  ruling/snapshots/prefer-while
  src/index.ts
  src/rules/prefer-while.ts
  tests/rules/prefer-while.test.ts
Labels: status: in progress

#58 add 'fixable' to prefer-immediate-return desc
  README.md
  docs/rules/prefer-immediate-return.md
Labels: status: in progress

#59 add semicolon to code fix of prefer-immediate-return
  src/rules/prefer-immediate-return.ts
  tests/rules/prefer-immediate-return.test.ts
Labels: status: in progress

#60 update .npmignore
  .npmignore
Labels: status: in progress

#62 Add 'eslintplugin' npm keyword
  package.json
Labels: status: in progress
